### ISSUE TITLE
Ambiguous parent-child-relation for Frame and MappedFrame

### ISSUE THREAD

**Issue by kubanrob** [ManyThreads/mythos#84]
MappedFrame does not include the size of the mapped Frame, so one might be unable if it belongs to a parent Frame or the child Frame if it's a successor of the child in the prefix list.

Proposed fix: include Frame size class in MappedFrame capability and return appropriate range (not `{addr, addr+1}`).

**Comment by kubanrob** [comment]
Might be `{addr, addr+size-1}` (to prevent confusion with original range).

**Comment by kubanrob** [comment]
> Might be `{addr, addr+size-1}` (to prevent confusion with original range).

This does not work because `addr` can be offset into the frame. We have enough bits to store the size class, but not enough for the start address of the frame.

Storing the offset when mapping the frame into the table might be used to recover the frames start address.

**Comment by kubanrob** [comment]
The offset into the frame might be up to 512 GiB big (biggest frame size). Divided through the smallest possible mapping alignment (4 KiB), this takes up  27 bit to store.

For a mapped frame, we need the index into the table (9 bit). This already 4 bit to much. For the correct range, we also need the size index (2 bit).
We can get rid of the mapped bit using the address of a member of the PageMap for mapped frames instead of the address of PageMap itself (similar to Frame in MemoryRegion).

There is also not enough free bits in the page table entries.

This problem can be solved:
- By restricting the size index to 2 (1 GB), but this leads to a lot (512x) of additional Frame capabilities if we have a huge RAM.
- Getting rid of the index. This is possible by using the Entry address for the range calculation, but is conceptually a bit strange.

**Comment by rottaran** [comment]
For the mapped frame we can store the original's address and size in just the 31 bits of the capability data. The capability pointer has to point to the page map in order to be able to unmap revoked frames. Therefore all frames and frame-alike kernel objects have to adhere to this scheme if we want to be able to report back the correct address range for the mapped frame. 

Memory regions have to be at least 4GB big to support kernel memory. Therefore 20 bits are needed for the frame's offset in 4KiB granuarity. In order to store useful sizes beyond 4KiB, 2MiB, 1GiB, we would need 5 bits for 32 size classes. For example the number of 4KiB pages in a powers of two granularity. This leaves 6 bits for increasing the size of the memory region.

**Comment by rottaran** [comment]
The parentship test for frames and sub-frames is more inheritently broken: Suppose we have a frame A, first create a small sub-frame B with offset 0 and then create a larger sub-frame C at offset 0. In the capability list they will be stored in A-C-B order. Now C and B start at the same address and B is smaller than C. Hence, B is interpreted as child of C and will be revoked when C is revoked --- even though B was never created as child of C.

We will have to look into how seL4 solved this. They had more bits for capability data available for frames because they use a few bits as object type and then store just the 20bit frame offset. And their parentship test can in theory see that it is dealing with frame capabilities and could do some special case for this issue.

**Comment by rottaran** [comment]
seL4 prevents this situation: frames cannot have sub-frames, just mapped frames as reference. The device memory ranges are untyped memory that consists of its start, size and allocation watermark. Frames as well as untyped memory subranges are allocated along the watermark and, hence, cannot overlap. 

Unfortunately, our capability design do not allow to store the watermark in the capability data. Hence, we cannot support a deep hierarchy of sub-ranges. We could add a watermark allocation to the device memory regions such that only frames can be allocated. The frame implementation can be flightweight without individual frame kernel objects. A little bit of hierarchy is possible when prohibiting sub-frames and overlapping frames: The derived and derived-referenced frame capabilities can be restricted to a sub-range of the original frame. When mapping a frame, it can be further restricted to a sub-range. Mapped frames need to report only its actual physical start address and size, which is easily available in the page map.

The frame capability data should be structured like this: 1 bit for writable, 1 bit for device memory, 5 bits for size class (power of two multiples of 4KiB), 25 bit for offset in its device memory region (as 4KiB count). This results in memory regions of 128GiB. The capabilitie's object pointer points to a flightweight helper in the memory region or in its kernel memory object. This allows to recycle the memory of deleted frames.

Frames allocated from kernel memory can still have arbitrary size if they are allocated as real kernel object. If the size is power-of-two, the flightweight pattern can be used.

**Comment by rottaran** [comment]
Basic support for issue #88 can be implemented when reworking the frame capability data.

**Comment by rottaran** [comment]
depends on issue #90 because we do not have enough space for all memory regions in the initial capability space.
